#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-cobs
Version  : 1.3.9
Release  : 50
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/cobs_1.3-9.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/cobs_1.3-9.tar.gz
Summary  : Constrained B-Splines (Sparse Matrix Based)
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-cobs-lib = %{version}-%{release}
Requires: R-SparseM
Requires: R-quantreg
BuildRequires : R-SparseM
BuildRequires : R-quantreg
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Linear Programming and Sparse Matrices.

%package lib
Summary: lib components for the R-cobs package.
Group: Libraries

%description lib
lib components for the R-cobs package.


%prep
%setup -q -n cobs
pushd ..
cp -a cobs buildavx2
popd
pushd ..
cp -a cobs buildavx512
popd
pushd ..
cp -a cobs buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735105825

%install
export SOURCE_DATE_EPOCH=1735105825
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/cobs/CITATION
/usr/lib64/R/library/cobs/DESCRIPTION
/usr/lib64/R/library/cobs/INDEX
/usr/lib64/R/library/cobs/Meta/Rd.rds
/usr/lib64/R/library/cobs/Meta/data.rds
/usr/lib64/R/library/cobs/Meta/features.rds
/usr/lib64/R/library/cobs/Meta/hsearch.rds
/usr/lib64/R/library/cobs/Meta/links.rds
/usr/lib64/R/library/cobs/Meta/nsInfo.rds
/usr/lib64/R/library/cobs/Meta/package.rds
/usr/lib64/R/library/cobs/NAMESPACE
/usr/lib64/R/library/cobs/R/cobs
/usr/lib64/R/library/cobs/R/cobs.rdb
/usr/lib64/R/library/cobs/R/cobs.rdx
/usr/lib64/R/library/cobs/data/Rdata.rdb
/usr/lib64/R/library/cobs/data/Rdata.rds
/usr/lib64/R/library/cobs/data/Rdata.rdx
/usr/lib64/R/library/cobs/help/AnIndex
/usr/lib64/R/library/cobs/help/aliases.rds
/usr/lib64/R/library/cobs/help/cobs.rdb
/usr/lib64/R/library/cobs/help/cobs.rdx
/usr/lib64/R/library/cobs/help/paths.rds
/usr/lib64/R/library/cobs/html/00Index.html
/usr/lib64/R/library/cobs/html/R.css
/usr/lib64/R/library/cobs/scripts/README
/usr/lib64/R/library/cobs/scripts/roof.R
/usr/lib64/R/library/cobs/scripts/temp.R
/usr/lib64/R/library/cobs/scripts/wind.R
/usr/lib64/R/library/cobs/tests/0_pt-ex.R
/usr/lib64/R/library/cobs/tests/README
/usr/lib64/R/library/cobs/tests/ex1.R
/usr/lib64/R/library/cobs/tests/ex2-long.R
/usr/lib64/R/library/cobs/tests/ex3.R
/usr/lib64/R/library/cobs/tests/ex3.Rout.save
/usr/lib64/R/library/cobs/tests/multi-constr.R
/usr/lib64/R/library/cobs/tests/multi-constr.Rout.save
/usr/lib64/R/library/cobs/tests/roof.R
/usr/lib64/R/library/cobs/tests/roof.Rout.save
/usr/lib64/R/library/cobs/tests/small-ex.R
/usr/lib64/R/library/cobs/tests/small-ex.Rout.save
/usr/lib64/R/library/cobs/tests/spline-ex.R
/usr/lib64/R/library/cobs/tests/spline-ex.Rout.save
/usr/lib64/R/library/cobs/tests/temp.R
/usr/lib64/R/library/cobs/tests/temp.Rout.save
/usr/lib64/R/library/cobs/tests/wind.R
/usr/lib64/R/library/cobs/util.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/cobs/libs/cobs.so
/V4/usr/lib64/R/library/cobs/libs/cobs.so
/VA/usr/lib64/R/library/cobs/libs/cobs.so
/usr/lib64/R/library/cobs/libs/cobs.so
